### ISSUE TITLE
Missing leading / in the generated basePath

### ISSUE THREAD

**Issue by Nyamiou** [seedstack/swagger-addon#7]
For an application where the REST path is "/api" and the default context path "/", the generated JSON swagger contains the basePath "api". This is invalid as the specification says that this field must start with a "/", it should therefore be "/api".

**Comment by Nyamiou** [comment]
Link to the specific paragraph of the specification: https://swagger.io/docs/specification/2-0/api-host-and-base-path/#basePath

**Comment by adrienlauer** [comment]
Fixed by #8
